object Food extends CommandRead {
  def main (args: Array[String]) {
    PANEL("P", 640, 480)

    NEWCIRCLE WITHNAME "PLATERIM" AT (20,10) RADIUS 90 COLOR "Black"
    NEWCIRCLE WITHNAME "PLATEINSIDE" AT (30,20) RADIUS 80 COLOR "Gray"
    MAKE DUPLICATE "PLATE" FROM ("PLATERIM", "PLATEINSIDE")
    
    NEWOVAL WITHNAME "EGGWHITE" AT (50,50) RADIUSX 40 RADIUSY 20 COLOR "Macaw Blue Green"
    NEWOVAL WITHNAME "EGGYOLK" AT(70,55) RADIUSX 20 RADIUSY 10 COLOR "Light Sea Green"
    NEWOVAL WITHNAME "EGGWHITE2" AT (85,40) RADIUSX 40 RADIUSY 20 COLOR "Macaw Blue Green"
    NEWOVAL WITHNAME "EGGYOLK2" AT(105,45) RADIUSX 20 RADIUSY 10 COLOR "Light Sea Green"
    MAKE DUPLICATE "EGGS" FROM ("EGGWHITE", "EGGWHITE2", "EGGYOLK", "EGGYOLK2")
    
    NEWOVAL WITHNAME "HAMFRONT" AT (65,100) RADIUSX 20 RADIUSY 30 COLOR "Blue Green"
    NEWOVAL WITHNAME "HAMOUTLINE" AT (64,99) RADIUSX 22 RADIUSY 32 COLOR "Light Sea Green"
    NEWCIRCLE WITHNAME "HAMFRONTDOT" AT (76,121) RADIUS 8 COLOR "Light Sea Green"
    NEWOVAL WITHNAME "HAMBODY" AT (70,103) RADIUSX 40 RADIUSY 20 COLOR "Blue Green"
    NEWOVAL WITHNAME "HAMBODY2" AT (70,110) RADIUSX 40 RADIUSY 20 COLOR "Blue Green"
    NEWOVAL WITHNAME "HAMBODY3" AT (70,117) RADIUSX 40 RADIUSY 20 COLOR "Blue Green"
    MAKE DUPLICATE "HAM" FROM ("HAMBODY", "HAMBODY2", "HAMBODY3", "HAMOUTLINE", "HAMFRONT", "HAMFRONTDOT")
    
    NEWRECT WITHNAME "FORKBASE" AT (250,140) WIDTH 8 HEIGHT 70 COLOR "Gray"
    NEWRECT WITHNAME "FORKSIDE" AT (240,140) WIDTH 28 HEIGHT 8 COLOR "Gray"
    NEWRECT WITHNAME "FORKPRONG1" AT (240,120) WIDTH 8 HEIGHT 20 COLOR "Gray"
    NEWRECT WITHNAME "FORKPRONG2" AT (250,120) WIDTH 8 HEIGHT 20 COLOR "Gray"
    NEWRECT WITHNAME "FORKPRONG3" AT (260,120) WIDTH 8 HEIGHT 20 COLOR "Gray"
    MAKE DUPLICATE "FORK" FROM ("FORKBASE", "FORKSIDE", "FORKPRONG1", "FORKPRONG2", "FORKPRONG3")
    
    MAKE DUPLICATE "KNIFE"
    NEWRECT WITHNAME "KNIFEBASE" AT (287, 121) WIDTH 8 HEIGHT 89 COLOR "Gray"
    GET COMPOSITE "KNIFE" ADD "KNIFEBASE"
    SETVAR("i", 1)
    PATTERN("i", 5) {
      NEWTRI WITHNAME "T" AT (280, GETVAR("i") * 10 + 110) BASE 10 HEIGHT 10 SETROTATE 25 COLOR "Gray"
      GET COMPOSITE "KNIFE" ADD "T"
    }
    
    DRAWTOPANEL("PLATE", "P")
    DRAWTOPANEL("EGGS", "P")
    DRAWTOPANEL("HAM", "P")
    DRAWTOPANEL("FORK", "P")
    DRAWTOPANEL("KNIFE", "P")
  }
}
