object PresentationInfoSlide extends CommandRead {
  def main (args: Array[String]) {
    PANEL("P", 1260, 720);
    SETPANEL( "P")
    
    NEWCIRCLE WITHNAME "TEALTOPLEFT" RADIUS 100 COLOR "presentation aqua" AT (75, -75) SCALE 1.5
    NEWCIRCLE WITHNAME "TEALTOPLEFTINSIDE" RADIUS 40 COLOR "WHITE" AT (165, 15) SCALE 1.5
    
    NEWCIRCLE WITHNAME "TOP LEFT BLUE OUTLINE" RADIUS 35 COLOR "PRESENTATION BLUE" AT (338, 38) FILLSTATE "OUTLINE" SCALE 1.5
    NEWCIRCLE WITHNAME "TOP LEFT BLUE" RADIUS 30 COLOR "PRESENTATION BLUE" AT (345, 45) SCALE 1.5

    NEWCIRCLE WITHNAME "ORANGELEFT" RADIUS 50 COLOR "PRESENTATION ORANGE" AT (-8, 135) SCALE 1.5
    
    NEWCIRCLE WITHNAME "LEFTYELLOW" RADIUS 30 COLOR "PRESENTATION YELLOW" AT (135, 315) SCALE 1.5
    NEWCIRCLE WITHNAME "LEFTYELLOWCENTER" RADIUS 20 COLOR "WHITE" AT (150, 330) SCALE 1.5
    
    NEWCIRCLE WITHNAME "LEFTGREEN OUTLINE" RADIUS 35 COLOR "PRESENTATION LIME" AT (195, 360) FILLSTATE "OUTLINE" SCALE 1.5
    
    NEWCIRCLE WITHNAME "LEFT FUSCIA" RADIUS 15 COLOR "PRESENTATION FUSCIA" AT ( 113, 345) SCALE 1.5
    
    NEWCIRCLE WITHNAME "LEFT BOTTOM LIME" RADIUS 60 COLOR "PRESENTATION LIME" AT (15, 570) SCALE 1.5

    NEWCIRCLE WITHNAME "LEFT BOTTOM GREEN" RADIUS 25 COLOR "PRESENTATION GREEN" AT (225, 525) SCALE 1.5

    NEWCIRCLE WITHNAME "LEFT BOTTOM GREEN CENTER" RADIUS 5 COLOR "WHITE" AT (255, 555) SCALE 1.5

    NEWCIRCLE WITHNAME "TOP RIGHT BLUE" RADIUS 30 COLOR "PRESENTATION BLUE" AT (1155, -38) SCALE 1.5
    NEWCIRCLE WITHNAME "TOP RIGHT BLUE CENTER" RADIUS 15 COLOR "WHITE" AT (1178, -15) SCALE 1.5
    
    NEWCIRCLE WITHNAME "TOP RIGHT YELLOW" RADIUS 20 COLOR "PRESENTATION YELLOW" AT (1080, 40) SCALE 1.5

    NEWCIRCLE WITHNAME "TOP RIGHT ORANGE OUTLINE" RADIUS 17 COLOR "PRESENTATION ORANGE" AT (1110, 98) FILLSTATE "OUTLINE" SCALE 1.5

    NEWCIRCLE WITHNAME "RIGHT TEAL" RADIUS 15 COLOR "PRESENTATION AQUA" AT (1230, 129) SCALE 1.5
    
    NEWCIRCLE WITHNAME "LEFT LIME" RADIUS 7 COLOR "PRESENTATION LIME" AT ( 1200, 180) SCALE 1.5

    
    DRAW ("TEALTOPLEFT")
    DRAW ("TEALTOPLEFTINSIDE")
    DRAW ("TOP LEFT BLUE")
    DRAW ("TOP LEFT BLUE OUTLINE")
    DRAW ("ORANGELEFT")
    DRAW ("LEFTYELLOW")
    DRAW ("LEFTYELLOWCENTER")
    DRAW ("LEFTGREEN OUTLINE")
    DRAW ("LEFT FUSCIA")
    DRAW ("LEFT BOTTOM LIME")
    DRAW ("LEFT BOTTOM GREEN")
    DRAW ("LEFT BOTTOM GREEN CENTER")
    
    
    
    DRAW ("TOP RIGHT BLUE")
    DRAW ("TOP RIGHT BLUE CENTER")
    DRAW ("TOP RIGHT YELLOW" )
    DRAW ("TOP RIGHT ORANGE OUTLINE")
    DRAW ("RIGHT TEAL")
    DRAW ("LEFT LIME")
  }
  
}
