object WithAMouse extends CommandRead {
  def main (args: Array[String]) {
    PANEL("P", 640, 480);

    NEWOVAL WITHNAME "BODY" RADIUSX 20 RADIUSY 50 COLOR "GRAY GOOSE" SETROTATE -30 AT (100, 100)
    NEWCIRCLE WITHNAME "LEFTEAR" RADIUS 15 COLOR "GRAY GOOSE" AT (53, 35)
    NEWCIRCLE WITHNAME "LEFTEARINNER" RADIUS 10 COLOR "LIGHT PINK" AT (60, 42)
    NEWCIRCLE WITHNAME "RIGHTEAR" RADIUS 17 COLOR "GRAY GOOSE" AT (90, 32)
    NEWCIRCLE WITHNAME "RIGHTEARINNER" RADIUS 12 COLOR "LIGHT PINK" AT (93, 40)
    NEWRECT WITHNAME "NECK" HEIGHT 40 WIDTH 10 COLOR "GRAY GOOSE" SETROTATE -20 AT (85, 70)
    NEWOVAL WITHNAME "LEG" RADIUSX 15 RADIUSY 20 COLOR "GRAY CLOUD" SETROTATE -45 AT(110, 160)
    NEWOVAL WITHNAME "REARFOOT" RADIUSX 15 RADIUSY 4 COLOR "GRAY CLOUD" AT(70, 185)
    NEWOVAL WITHNAME "HEAD" RADIUSX 18 RADIUSY 21 COLOR "GRAY GOOSE" AT(70, 50)
    NEWTRI WITHNAME "SNOUT" BASE 20 HEIGHT 35 COLOR "GRAY GOOSE" SETROTATE -70 AT(58, 58)
    NEWOVAL WITHNAME "NOSE" RADIUSX 5 RADIUSY 3 COLOR "PINK BOW" AT(53, 68);
    NEWCIRCLE WITHNAME "LEFTEYE" RADIUS 2 COLOR "BLACK" AT (75, 65)
    NEWCIRCLE WITHNAME "RIGHTEYE" RADIUS 2 COLOR "BLACK" AT (85, 65)
    NEWSQUIGGLE WITHNAME "TAIL" HEIGHT 90 WIDTH 15 PERIODS 2 IS "VERTICAL" THICKNESS 4 COLOR "GRAY GOOSE" AT (210, 130) SETROTATE 35
    NEWRECT WITHNAME "LEFTLEG" HEIGHT 75 WIDTH 8 COLOR "GRAY GOOSE" AT (63, 110)
    NEWOVAL WITHNAME "LEFTFOOT" RADIUSX 6 RADIUSY 4 COLOR "GRAY GOOSE" AT (58, 180)
    NEWCIRCLE WITHNAME "MOUTH" RADIUS 6 COLOR "BLACK" AT(50, 75)
    NEWRECT WITHNAME "MOUTHTOP" WIDTH 15 HEIGHT 8 COLOR "GRAY GOOSE" AT( 47, 73) SETROTATE -20

    MAKE DUPLICATE "MOUSE" FROM("BODY", "LEG", "NECK", "SNOUT", "NOSE", "LEFTEAR","LEFTEARINNER", "RIGHTEAR", "RIGHTEARINNER", "HEAD",
        "LEFTEYE", "RIGHTEYE", "TAIL", "LEFTLEG", "LEFTFOOT", "REARFOOT", "MOUTH", "MOUTHTOP");
    DRAWTOPANEL("MOUSE", "P", 0, 0);


        NEWCIRCLE WITHNAME "PLATERIM" AT (20,10) RADIUS 90 COLOR "Black"
    NEWCIRCLE WITHNAME "PLATEINSIDE" AT (30,20) RADIUS 80 COLOR "Gray"
    MAKE DUPLICATE "PLATE" FROM ("PLATERIM", "PLATEINSIDE")
    
    NEWOVAL WITHNAME "EGGWHITE" AT (50,50) RADIUSX 40 RADIUSY 20 COLOR "Macaw Blue Green"
    NEWOVAL WITHNAME "EGGYOLK" AT(70,55) RADIUSX 20 RADIUSY 10 COLOR "Light Sea Green"
    NEWOVAL WITHNAME "EGGWHITE2" AT (85,40) RADIUSX 40 RADIUSY 20 COLOR "Macaw Blue Green"
    NEWOVAL WITHNAME "EGGYOLK2" AT(105,45) RADIUSX 20 RADIUSY 10 COLOR "Light Sea Green"
    MAKE DUPLICATE "EGGS" FROM ("EGGWHITE", "EGGWHITE2", "EGGYOLK", "EGGYOLK2")
    
    NEWOVAL WITHNAME "HAMFRONT" AT (65,100) RADIUSX 20 RADIUSY 30 COLOR "Blue Green"
    NEWOVAL WITHNAME "HAMOUTLINE" AT (64,99) RADIUSX 22 RADIUSY 32 COLOR "Light Sea Green"
    NEWCIRCLE WITHNAME "HAMFRONTDOT" AT (76,121) RADIUS 8 COLOR "Light Sea Green"
    NEWOVAL WITHNAME "HAMBODY" AT (70,103) RADIUSX 40 RADIUSY 20 COLOR "Blue Green"
    NEWOVAL WITHNAME "HAMBODY2" AT (70,110) RADIUSX 40 RADIUSY 20 COLOR "Blue Green"
    NEWOVAL WITHNAME "HAMBODY3" AT (70,117) RADIUSX 40 RADIUSY 20 COLOR "Blue Green"
    MAKE DUPLICATE "HAM" FROM ("HAMBODY", "HAMBODY2", "HAMBODY3", "HAMOUTLINE", "HAMFRONT", "HAMFRONTDOT")
    
    NEWRECT WITHNAME "FORKBASE" AT (250,140) WIDTH 8 HEIGHT 70 COLOR "Gray"
    NEWRECT WITHNAME "FORKSIDE" AT (240,140) WIDTH 28 HEIGHT 8 COLOR "Gray"
    NEWRECT WITHNAME "FORKPRONG1" AT (240,120) WIDTH 8 HEIGHT 20 COLOR "Gray"
    NEWRECT WITHNAME "FORKPRONG2" AT (250,120) WIDTH 8 HEIGHT 20 COLOR "Gray"
    NEWRECT WITHNAME "FORKPRONG3" AT (260,120) WIDTH 8 HEIGHT 20 COLOR "Gray"
    MAKE DUPLICATE "FORK" FROM ("FORKBASE", "FORKSIDE", "FORKPRONG1", "FORKPRONG2", "FORKPRONG3")
    
    MAKE DUPLICATE "KNIFE"
    NEWRECT WITHNAME "KNIFEBASE" AT (287, 121) WIDTH 8 HEIGHT 89 COLOR "Gray"
    GET COMPOSITE "KNIFE" ADD "KNIFEBASE"
    SETVAR("i", 1)
    PATTERN("i", 5) {
      NEWTRI WITHNAME "T" AT (280, GETVAR("i") * 10 + 110) BASE 10 HEIGHT 10 SETROTATE 25 COLOR "Gray"
      GET COMPOSITE "KNIFE" ADD "T"
    }
   
    MAKE A "GEANDHAM" FROM ("PLATE", "EGGS", "HAM", "FORK", "KNIFE") SCALE .5 AT ( 200, 50);
    

    DRAWTOPANEL("GEANDHAM", "P") 
    
  }
}




















